/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system;
import java.util.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
public class Product_Page extends javax.swing.JFrame {
Connection con;
ResultSet res;
Statement stm;
//JTextField pname,edt,frdt,todt;
//JLabel plname,ledt,lfrdt,ltodt;
Color c;
Calendar cal;
int dd,mm,yy;
String dt,mnth;
    public Product_Page() {
        initComponents();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.gray);
        c=new Color(255, 255, 255);
        cal=new GregorianCalendar();
        dd=cal.get(cal.DAY_OF_MONTH);
        mm=cal.get(cal.MONTH);
        yy=cal.get(cal.YEAR);
        plname.setForeground(c);
        plname.setBounds(20, 30, 200, 25);
        pname.setBounds(140, 30, 160, 25);
        ledt.setBounds(300,30,150,25);
        edt.setBounds(370, 30, 150, 25);
        dto.setBounds(520, 30, 80, 25);
        dtext.setBounds(570, 30, 150, 25);
        dfm.setBounds(720, 30,50, 25);
        ftext.setBounds(770, 30, 150, 25);
        detail.setBounds(0, 0, 950, 80);
        //
        detail.add(dto);
        detail.add(dtext);
        detail.add(dfm);
        detail.add(ftext);
        detail.add(plname);
        detail.add(ledt);
        detail.add(pname);
        detail.add(edt);
        edt.setText(convertDate(dd, mm, yy));
        dtext.setText(convertDate(dd, mm, yy));
        jScrollPane1.setBounds(0, 80, 950, 250);
        dataTab.setBounds(0,0, 950, 250);
        jScrollPane1.add(dataTab);
        this.add(detail);
        this.add(jScrollPane1);
        //JOptionPane.showMessageDialog(rootPane, dd+"-"+mm+"-"+yy);
    }
    public String convertDate(int dd,int mm,int yy)//this method is used to found the date in dd-mm-yy format
    {
        switch(mm)
        {
            case 0:return dd+"-jan-"+yy;
            case 1:return dd+"-feb-"+yy;
            case 2:return dd+"-mar-"+yy;   
            case 3:return dd+"-apr-"+yy;
            case 4:return dd+"-may-"+yy;
            case 5:return dd+"-jun-"+yy;
            case 6:return dd+"-jul-"+yy;
            case 7:return dd+"-aug-"+yy;
            case 8:return dd+"-sep-"+yy;
            case 9:return dd+"-oct-"+yy;
            case 10:return dd+"-nov-"+yy;
            case 11:return dd+"-dec-"+yy;
            default: return null;
        }
        //return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detail = new javax.swing.JPanel();
        plname = new javax.swing.JLabel();
        edt = new javax.swing.JTextField();
        ledt = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        dto = new javax.swing.JLabel();
        dtext = new javax.swing.JTextField();
        dfm = new javax.swing.JLabel();
        ftext = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ":: Search Details ::", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, null, java.awt.Color.red));

        plname.setText("Enter Product name:");

        edt.setText("Enter date");

        ledt.setText("Enter Date:");

        pname.setText("Enter Name");

        dto.setText("Date to:");

        dfm.setText("From:");

        javax.swing.GroupLayout detailLayout = new javax.swing.GroupLayout(detail);
        detail.setLayout(detailLayout);
        detailLayout.setHorizontalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plname)
                .addGap(18, 18, 18)
                .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ledt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dto)
                .addGap(18, 18, 18)
                .addComponent(dtext, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dfm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftext, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        detailLayout.setVerticalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plname)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ledt)
                    .addComponent(edt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dto)
                    .addComponent(dtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dfm)
                    .addComponent(ftext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dataTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dataTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Product_Page().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTab;
    private javax.swing.JPanel detail;
    private javax.swing.JLabel dfm;
    private javax.swing.JTextField dtext;
    private javax.swing.JLabel dto;
    private javax.swing.JTextField edt;
    private javax.swing.JTextField ftext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ledt;
    private javax.swing.JLabel plname;
    private javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables
}
