/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mantu
 */
public class set_per extends javax.swing.JFrame {
Connection con;
Vector row,col;
    public set_per() throws ClassNotFoundException {
        super("Percentage...!");
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setBounds(150, 150, 475, 550);
        Class.forName("oracle.jdbc.OracleDriver");
        getContentPane().setBackground(new Color(10,179,79));
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon1.png"));
    }
    public void setconnect(String uname,String pass) //this method for get a connection
    {
        try{
            String ser="jdbc:oracle:thin:@localhost:1521:XE";
            con=DriverManager.getConnection(ser, uname, pass);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
    public void setPercentage()//this method for set Percentage to the user
    {
        try{
            String sql="insert into per_tab values(?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, (String)jComboBox1.getSelectedItem());
            pst.setString(2, (String)jComboBox2.getSelectedItem());
            pst.setDouble(3, Double.parseDouble(jTextField1.getText()));
            int x=pst.executeUpdate();
            if(x>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Percentage set For The customer:- "+(String)jComboBox1.getSelectedItem()+" ...!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
    public void setCustomer()//set Customer Names...!
    {
        try{
            ResultSet res=con.createStatement().executeQuery("select Cname from CUSTOMER_TAB");
            while(res.next())
            {
                jComboBox1.addItem(res.getString("Cname"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
     public void setProduct()//set Product Names...!
    {
        try{
            ResultSet res=con.createStatement().executeQuery("select Pname from PURCHASE_TAB");
            while(res.next())
            {
                jComboBox2.addItem(res.getString("Pname"));
            }
            res.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
     public void setColumn()
     {
         try{
         col=new Vector();
         row=new Vector();
         row.clear();
         col.add("Sl/no");
         col.add("Customer Name");
         col.add("Product name");
         col.add("Percentage");
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, e.toString());
         }
     }
     public void viewPerData()//view All the percentage information for a customer
     {
      try{
          setColumn();
          Vector v=null;
          int x=1;
          Statement stm=con.createStatement();
            ResultSet res=stm.executeQuery("select * from per_tab");
            while(res.next())
            {
                v=new Vector();
                v.add(x++);
                v.add(res.getString("Cname"));
                v.add(res.getString("Pname"));
                v.add(res.getDouble("per"));
                row.add(v);
            }
            jTable1.setModel(new DefaultTableModel(row,col));
            res.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }   
     }
     public void updateData()//update the percentage
     {
         try{
             String cname=(String)jComboBox1.getSelectedItem();
             String pname=(String)jComboBox2.getSelectedItem();
             String sql="update per_tab set per="+jTextField1.getText()+" where Cname='"+cname+"' and pname='"+pname+"'";
             Statement stm=con.createStatement();
             int x=stm.executeUpdate(sql);
             if(x>0){
                 JOptionPane.showMessageDialog(rootPane, "Percentage Updated...!");
             }
         }catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, e.toString());
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Choose Name:");

        jComboBox1.setEditable(true);

        jLabel2.setText("Set Percentage:");

        jButton1.setMnemonic('S');
        jButton1.setText("Set");
        jButton1.setToolTipText("Set Percentage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setEditable(true);

        jLabel3.setText("Choose Product:");

        jButton2.setMnemonic('U');
        jButton2.setText("Update");
        jButton2.setToolTipText("Update percentage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setPercentage();
        viewPerData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setCustomer();
        setProduct();
        viewPerData();
        //setColumn();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       updateData();
       viewPerData();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void removePerData()//remove the percentage information
    {
         int res=JOptionPane.showConfirmDialog(rootPane, "Do you Want To Delete ?", "Remove Percentage.", JOptionPane.YES_NO_OPTION);
         if(res==JOptionPane.YES_OPTION)
         {
          try{
              Statement pst=con.createStatement();
              int x=pst.executeUpdate("delete  from Per_tab where cname='"+(String)jComboBox1.getSelectedItem()+"' and pname='"+(String)jComboBox2.getSelectedItem()+"'");
              if(x!=0)
              {
                  JOptionPane.showMessageDialog(rootPane, "Delete Successfully...!", "Remove Percentage.", JOptionPane.INFORMATION_MESSAGE);
              }
              else
              {
                  JOptionPane.showMessageDialog(rootPane, "Record Not Found...!", "Remove Percentage.", JOptionPane.ERROR_MESSAGE);
              }
          }catch(Exception e)
          {
              JOptionPane.showMessageDialog(rootPane,  e.toString(),"Remove Percentage.", JOptionPane.ERROR_MESSAGE);
          }
             
         }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        removePerData();
        viewPerData();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(set_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(set_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(set_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(set_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new set_per().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(set_per.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
